title: Santi Gonzalez
description: My Personal Webpage
author: Santi Gonzalez
logo: /static/img/avatar.png
github: https://github.com/santipaprika
about: Graphics and game developer

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: aboutsanti
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 10
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
